use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!       #忽略所有警告

target 'JWPermissionKit_Example' do
  pod 'JWPermissionKit/Photos', :path => '../'
  pod 'JWPermissionKit/Camera', :path => '../'
  pod 'JWPermissionKit/Microphone', :path => '../'
  pod 'JWPermissionKit/RxSwift', :path => '../'
  pod 'SnapKit'
  target 'JWPermissionKit_Tests' do
    inherit! :search_paths

    
  end
end
